/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EasyfillRouteImport } from './routes/easyfill'
import { Route as FindRouteImport } from './routes/find'
import { Route as BookHospitalIdRouteImport } from './routes/book.$hospitalId'
import { Route as HospitalIdRouteImport } from './routes/hospital.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EasyfillRoute = EasyfillRouteImport.update({
  id: '/easyfill',
  path: '/easyfill',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const BookHospitalIdRoute = BookHospitalIdRouteImport.update({
  id: '/book/$hospitalId',
  path: '/book/$hospitalId',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIdRoute = HospitalIdRouteImport.update({
  id: '/hospital/$id',
  path: '/hospital/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/easyfill': typeof EasyfillRoute
  '/find': typeof FindRoute
  '/book/$hospitalId': typeof BookHospitalIdRoute
  '/hospital/$id': typeof HospitalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/easyfill': typeof EasyfillRoute
  '/find': typeof FindRoute
  '/book/$hospitalId': typeof BookHospitalIdRoute
  '/hospital/$id': typeof HospitalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/easyfill': typeof EasyfillRoute
  '/find': typeof FindRoute
  '/book/$hospitalId': typeof BookHospitalIdRoute
  '/hospital/$id': typeof HospitalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/compare'
    | '/easyfill'
    | '/find'
    | '/book/$hospitalId'
    | '/hospital/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/compare'
    | '/easyfill'
    | '/find'
    | '/book/$hospitalId'
    | '/hospital/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/compare'
    | '/easyfill'
    | '/find'
    | '/book/$hospitalId'
    | '/hospital/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  EasyfillRoute: typeof EasyfillRoute
  FindRoute: typeof FindRoute
  BookHospitalIdRoute: typeof BookHospitalIdRoute
  HospitalIdRoute: typeof HospitalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easyfill': {
      id: '/easyfill'
      path: '/easyfill'
      fullPath: '/easyfill'
      preLoaderRoute: typeof EasyfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$hospitalId': {
      id: '/book/$hospitalId'
      path: '/book/$hospitalId'
      fullPath: '/book/$hospitalId'
      preLoaderRoute: typeof BookHospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/$id': {
      id: '/hospital/$id'
      path: '/hospital/$id'
      fullPath: '/hospital/$id'
      preLoaderRoute: typeof HospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  EasyfillRoute: EasyfillRoute,
  FindRoute: FindRoute,
  BookHospitalIdRoute: BookHospitalIdRoute,
  HospitalIdRoute: HospitalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
